language: python

git:
  depth: false
notifications:
  email:
    on_success: never
    on_failure: always

install:
  - pip install ansible
  - curl -L -o packer.zip https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_linux_amd64.zip && unzip -d bin packer.zip

script:
  - ./build.sh
